In [2]:
import numpy as np
X = np.matrix('1,.9,.8; 1,.5,.6; 1,.7,.7; 1,.6,.5')
Y = np.matrix('.95; .5; .75; .5')
a = np.linalg.inv(np.dot(X.T, X))
b = np.dot(X.T, Y)
w = np.dot(a, b)
sqrNormW = np.linalg.norm(w)**2
print(w)
print(sqrNormW)

[[-0.33611111]
 [ 0.72222222]
 [ 0.80555556]]
1.2834953703703522


In [4]:
import numpy as np
X = np.matrix('1,.9,.8; 1,.5,.6; 1,.7,.7; 1,.6,.5')
Y = np.matrix('.95; .5; .75; .5')
alpha = 10
a = np.linalg.inv(np.dot(X.T, X) + alpha*np.identity(3))
b = np.dot(X.T, Y)
w = np.dot(a, b)
sqrNormW = np.linalg.norm(w)**2
print(w)
print(sqrNormW)
# smaller sqaured norm since a larger alpha value puts more emphasis on minimizing
# the squared norm.

[[0.15173996]
 [0.11161762]
 [0.10548963]]
0.046611569478940636


In [37]:
import numpy as np
X = np.matrix('1,.9,.8; 1,.5,.6; 1,.7,.7; 1,.6,.5')
Y = np.matrix('.95; .5; .75; .5')
alpha = 10
a = np.linalg.inv(np.dot(X.T, X) + alpha*np.identity(3))
b = np.dot(X.T, Y) + alpha
w = np.dot(a, b)
sqrNormW = np.linalg.norm(w)**2
print(w)
print(sqrNormW)
# The weights increased compared to part b. Since we constrained our weights to
# be close to the vector of all ones. This is because the close w is to one,
# the smaller the square norm which will help minimize J.

[[0.62309692]
 [0.74566262]
 [0.75513617]]
1.5144931574175242


In [126]:
import numpy as np
def pi(i, x):
    a = np.exp(np.dot(w[i,:], x.T))
    b = 0
    for j in range(3):
        b += np.exp(np.dot(w[j,:], x.T))
    return a / b

x = np.matrix('1,1,2; 1,2,1; 1,2,2')
y = np.identity(3)
w = np.matrix('1,0,1; 1,1,1; 0,0,0').T

product = 1
for i in range(3):
    for j in range(3):
        product *= pi(j, x[i])**int(y[i,j])
        print(product)

print(product)
pi(0, x[1])

[[0.4223188]]
[[0.4223188]]
[[0.4223188]]
[[0.4223188]]
[[0.06561246]]
[[0.06561246]]
[[0.06561246]]
[[0.06561246]]
[[0.02770938]]
[[0.02770938]]


matrix([[0.4223188]])

In [32]:
pi(0, np.matrix('1,1,2'))

matrix([[0.4223188]])

In [124]:
def f(net):
    return 1 / (1 + np.exp(-net))

x = np.matrix('.9,.8; .5,.6; .7,.7; .6,.5')
y = np.matrix('.95; .5; .75; .5')
z = np.matrix('0,0')
o = np.matrix('0')
bh = np.matrix('0,0')
bo = np.matrix('0')
wh = np.matrix('0,0;0,0')
wo = np.matrix('0,0')

for i in range(2):
    for i in range(4):
        z = f(bh + (wh*x[i,:].T).T)
        o = f(bo + (wo*z.T).T)

        do = o*(1-o)*(o-y[i,:])
        dh = (z.T*(1-z)*(wo.T*do)).T

        bo = bo - do
        bh = bh - dh

        wo = wo - (z.T*do).T
        wh = wh - (x[i,:].T*dh).T

        print('\n#####################################\n')
        print('do')
        print(do)
        print('\ndh')
        print(dh)
        print('\nbo')
        print(bo)
        print('\nbh')
        print(bh)
        print('\nwo')
        print(wo)
        print('\nwh')
        print(wh)
        print('\nz')
        print(z)
        print('\no')
        print(o)


#####################################

do
[[-0.1125]]

dh
[[0. 0.]]

bo
[[0.1125]]

bh
[[0. 0.]]

wo
[[0.05625 0.05625]]

wh
[[0. 0.]
 [0. 0.]]

z
[[0.5 0.5]]

o
[[0.5]]

#####################################

do
[[0.01044736]]

dh
[[0.00029383 0.00029383]]

bo
[[0.10205264]]

bh
[[-0.00029383 -0.00029383]]

wo
[[0.05102632 0.05102632]]

wh
[[-0.00014692 -0.0001763 ]
 [-0.00014692 -0.0001763 ]]

z
[[0.5 0.5]]

o
[[0.54208767]]

#####################################

do
[[-0.05264308]]

dh
[[-0.00134309 -0.00134309]]

bo
[[0.15469572]]

bh
[[0.00104926 0.00104926]]

wo
[[0.07734101 0.07734101]]

wh
[[0.00079325 0.00076386]
 [0.00079325 0.00076386]]

z
[[0.49986998 0.49986998]]

o
[[0.53819188]]

#####################################

do
[[0.01424934]]

dh
[[0.00055103 0.00055103]]

bo
[[0.14044638]]

bh
[[0.00049823 0.00049823]]

wo
[[0.07020955 0.07020955]]

wh
[[0.00046263 0.00048835]
 [0.00046263 0.00048835]]

z
[[0.50047678 0.50047678]]

o
[[0.55776849]]

##########################

In [144]:
def f(net):
    return 1 / (1 + np.exp(-net))

x = np.matrix('.9,.8; .5,.6; .7,.7; .6,.5').T
y = np.matrix('.95; .5; .75; .5').T
z = np.matrix('0,0').T
o = 0
bh = np.matrix('0,0').T
bo = 0
wh = np.matrix('0,0;0,0')
wo = np.matrix('0,0').T

for i in range(2):
    for i in range(4):
        z = f(bh + np.dot(wh.T, x[:,i]))
        o = f(bo + np.dot(wo.T, z))

        do = o*(1-o)*(o-y[:,i])
        dh = np.dot(z.T, (1-z))[0,0]*(wo*do)

        bo = bo - do
        bh = bh - dh

        wo = wo - z*do
        wh = wh - np.dot(x[:,i], dh.T)

        print('\n#####################################\n')
        print('do')
        print(do)
        print('\ndh')
        print(dh)
        print('\nbo')
        print(bo)
        print('\nbh')
        print(bh)
        print('\nwo')
        print(wo)
        print('\nwh')
        print(wh)
        print('\nz')
        print(z)
        print('\no')
        print(o)


#####################################

do
[[-0.1125]]

dh
[[0.]
 [0.]]

bo
[[0.1125]]

bh
[[0.]
 [0.]]

wo
[[0.05625]
 [0.05625]]

wh
[[0. 0.]
 [0. 0.]]

z
[[0.5]
 [0.5]]

o
[[0.5]]

#####################################

do
[[0.01044736]]

dh
[[0.00029383]
 [0.00029383]]

bo
[[0.10205264]]

bh
[[-0.00029383]
 [-0.00029383]]

wo
[[0.05102632]
 [0.05102632]]

wh
[[-0.00014692 -0.00014692]
 [-0.0001763  -0.0001763 ]]

z
[[0.5]
 [0.5]]

o
[[0.54208767]]

#####################################

do
[[-0.05264308]]

dh
[[-0.00134309]
 [-0.00134309]]

bo
[[0.15469572]]

bh
[[0.00104926]
 [0.00104926]]

wo
[[0.07734101]
 [0.07734101]]

wh
[[0.00079325 0.00079325]
 [0.00076386 0.00076386]]

z
[[0.49986998]
 [0.49986998]]

o
[[0.53819188]]

#####################################

do
[[0.01424934]]

dh
[[0.00055103]
 [0.00055103]]

bo
[[0.14044638]]

bh
[[0.00049823]
 [0.00049823]]

wo
[[0.07020955]
 [0.07020955]]

wh
[[0.00046263 0.00046263]
 [0.00048835 0.00048835]]

z
[[0.50047678]
 [0.50047678